export const COUNTRIES = [
  'Afghanistan',
  'Africa Eastern and Southern',
  'Africa Western and Central',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Arab World',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas, The',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'British Virgin Islands',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Caribbean small states',
  'Cayman Islands',
  'Central African Republic',
  'Central Europe and the Baltics',
  'Chad',
  'Channel Islands',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo, Dem. Rep.',
  'Congo, Rep.',
  'Costa Rica',
  'Cote d\'Ivoire',
  'Croatia',
  'Cuba',
  'Curacao',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Early-demographic dividend',
  'East Asia & Pacific',
  'East Asia & Pacific (IDA & IBRD countries)',
  'East Asia & Pacific (excluding high income)',
  'Ecuador',
  'Egypt, Arab Rep.',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Euro area',
  'Europe & Central Asia',
  'Europe & Central Asia (IDA & IBRD countries)',
  'Europe & Central Asia (excluding high income)',
  'European Union',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'Fragile and conflict affected situations',
  'France',
  'French Polynesia',
  'Gabon',
  'Gambia, The',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guam',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heavily indebted poor countries (HIPC)',
  'High income',
  'Honduras',
  'Hong Kong SAR, China',
  'Hungary',
  'IBRD only',
  'IDA & IBRD total',
  'IDA blend',
  'IDA only',
  'IDA total',
  'Iceland',
  'India',
  'Indonesia',
  'Iran, Islamic Rep.',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea, Dem. People\'s Rep.',
  'Korea, Rep.',
  'Kosovo',
  'Kuwait',
  'Kyrgyz Republic',
  'Lao PDR',
  'Late-demographic dividend',
  'Latin America & Caribbean',
  'Latin America & Caribbean (excluding high income)',
  'Latin America & the Caribbean (IDA & IBRD countries)',
  'Latvia',
  'Least developed countries: UN classification',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Low & middle income',
  'Low income',
  'Lower middle income',
  'Luxembourg',
  'Macao SAR, China',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia, Fed. Sts.',
  'Middle East & North Africa',
  'Middle East & North Africa (IDA & IBRD countries)',
  'Middle East & North Africa (excluding high income)',
  'Middle income',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North America',
  'North Macedonia',
  'Northern Mariana Islands',
  'Norway',
  'Not classified',
  'OECD members',
  'Oman',
  'Other small states',
  'Pacific island small states',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Post-demographic dividend',
  'Pre-demographic dividend',
  'Puerto Rico',
  'Qatar',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten (Dutch part)',
  'Slovak Republic',
  'Slovenia',
  'Small states',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Asia',
  'South Asia (IDA & IBRD)',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'St. Kitts and Nevis',
  'St. Lucia',
  'St. Martin (French part)',
  'St. Vincent and the Grenadines',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa (IDA & IBRD countries)',
  'Sub-Saharan Africa (excluding high income)',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkiye',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Upper middle income',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela, RB',
  'Viet Nam',
  'Virgin Islands (U.S.)',
  'West Bank and Gaza',
  'World',
  'Yemen, Rep.',
  'Zambia',
  'Zimbabwe',
]
